### ISSUE TITLE
Issue with caching images loaded from URL.

### ISSUE THREAD

**Issue by ibrcic** [bumptech/glide#1360]
Hi, I am using Glide version 3.7.0 and have following issue.
I have an image that is displayed in some activity and is loaded from URL. Disk caching strategy is default, which should be ALL.

When user clicks on image I open new activity with same image in full screen mode loaded from the same URL. I was under impression that Glide should know that it is the same image and load it from cache but instead it loads the image again making a new request.

My understanding is that when cache strategy is ALL, image should be cached in resolution needed for original activity (RESULT) as well as in full resolution which is needed for new activity (SOURCE).

So why is new activity not using SOURCE image from cache but instead makes a new request?

My guess is that it is because image in new activity, even though it is whole image without cropping, is still different resolution than SOURCE. If that is the case, can I somehow force the Glide to use SOURCE from cache to load the image?

Thank  you!

**Comment by TWiStErRob** [comment]
> Disk caching strategy is default, which should be ALL.

No, it's RESULT, see `GenericRequestBuilder#diskCacheStrategy`.

> still different resolution than SOURCE

There's no resolution/dimensions involved when matching SOURCE cache, only the Url and signature.

>  can I somehow force the Glide to use SOURCE from cache to load the image?

Yes, enable via `.diskCacheStrategy(SOURCE)`, or `.diskCacheStrategy(ALL)`.

**Comment by ibrcic** [comment]
Thanks for quick answer, this should solve my problem.

I was under impression that default is ALL because it says so on the following link.
https://futurestud.io/blog/glide-caching-basics 
I guess you can't to anything about it if it is not your documentation.

**Comment by TWiStErRob** [comment]
Thanks for the source! It's in my work queue to proof-read their docs.

I know that they read their Disqus comments though, just notified them.

**Comment by TWiStErRob** [comment]
Doc is fixed already :)

Just saw your edit, double-check that your url is exactly the same, and are you sure that A populated the cache before you went to B?

**Comment by peitek** [comment]
Thanks for the info, appreciate it!

I'm not sure where I got the impression that `ALL` is the default. I tried to make sense of my notes, but I didn't source that info :/

**Comment by ibrcic** [comment]
I am not sure if I am doing something wrong but it is still not reading from cache. Just to make it clear:

Activity A - Activity where image is originally loaded
Activity B - Activity that opens up when original image is clicked.

Here is my code,

Activity A:
`        Glide.with(this)
.load(report.getDisplayImage())
               .crossFade(50)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(reportPhoto);
`

Activity B:
`  Glide.with(this)
                .load(imgUrl)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .listener( ... ) 
                .into(reportPhoto);
`

Still, Activity B loads images from url and not from cache. I check that by implementing listener, **boolean isFromMemoryCache** in onResourceReady() is false when I first open the image.

**Comment by ibrcic** [comment]
I did just that and URL is definitely the same. Images are generally about 2MP in size, let's say 1500 * 1200 approximately and are size of 300 - 600 kb.
Tried removing disk cache strategy from second call but results are the same.

**Comment by TWiStErRob** [comment]
Aha!, `isFromMemoryCache` is not how you check whether the image was loaded from disk cache; the name includes *memory* cache! RESULT disk cache and memory cache will only be hit if size, transformation, decoder, ... are all the same in two different loads, yours won't ever hit memory cache because the sizes are different.

Check out [debugging wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) to see how to check if it's really from disk or network.

**Comment by ibrcic** [comment]
Didn't even think about that!
Now that you said it, when I checked how fast are images loading visually it is pretty fast compared to when I didn't save ALL to cache in original request. I'll check if they are loaded from disk cache but it seems that that is the case.
Thank you for prompt help with my issue!
