### ISSUE TITLE
Change from Glide 4.2.0 to 4.3.0 = crash. Revert to 4.2.0 and all is fine again

### ISSUE THREAD

**Issue by MKevin3** [bumptech/glide#2548]
Android Studio 3.0
MacBook High Sierra 10.13.1 
Android emulator Nexus 5X API level 26
Run app using 
`implementation 'com.github.bumptech.glide:glide:4.2.0'`
Everything is fine but change to
`implementation 'com.github.bumptech.glide:glide:4.3.0'`
and it crashes for any image I attempt to display. Images are JPG files hosted by Amazon (cloudfront.net)
Placeholder image is 256x256 32-bit color PNG in the APK
Change back to 4.2.0, sync gradle, build app and it works perfectly again

```
11-01 13:56:52.545 16062-16199/{my app}.debug A/OpenGLRenderer: unknown bitmap configuration
11-01 13:56:52.545 16062-16199/{my app}..debug A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 16199 (glide-disk-cach)
11-01 13:56:52.565 16202-16202/? I/crash_dump32: obtaining output fd from tombstoned
11-01 13:56:52.565 1399-1399/? I//system/bin/tombstoned: received crash request for pid 16062
11-01 13:56:52.565 16202-16202/? I/crash_dump32: performing dump of process 16062 (target tid = 16199)
11-01 13:56:52.566 16202-16202/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-01 13:56:52.566 16202-16202/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.170720.005/4205617:user/release-keys'
11-01 13:56:52.566 16202-16202/? A/DEBUG: Revision: '0'
11-01 13:56:52.566 16202-16202/? A/DEBUG: ABI: 'x86'
11-01 13:56:52.566 16202-16202/? A/DEBUG: pid: 16062, tid: 16199, name: glide-disk-cach  >>> {my app}.debug <<<
11-01 13:56:52.566 16202-16202/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-01 13:56:52.567 16202-16202/? A/DEBUG: Abort message: 'unknown bitmap configuration'
11-01 13:56:52.567 16202-16202/? A/DEBUG:     eax 00000000  ebx 00003ebe  ecx 00003f47  edx 00000006
11-01 13:56:52.567 16202-16202/? A/DEBUG:     esi 00003f47  edi 928f95a8
11-01 13:56:52.568 16202-16202/? A/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
11-01 13:56:52.568 16202-16202/? A/DEBUG:     eip b5aebac4  ebp 928f95c8  esp 928f955c  flags 00000296
11-01 13:56:52.802 16202-16202/? A/DEBUG: backtrace:
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #00 pc 00000ac4  [vdso:b5aeb000] (__kernel_vsyscall+16)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #01 pc 00075b3c  /system/lib/libc.so (tgkill+28)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #02 pc 0001f04e  /system/lib/libc.so (abort+110)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #03 pc 00006a06  /system/lib/liblog.so (__android_log_assert+294)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #04 pc 0002784f  /system/lib/libhwui.so (_ZN7androidL14allocateBitmapEP8SkBitmapP12SkColorTablePF5sk_spINS_6BitmapEEjRK11SkImageInfojS3_E+191)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #05 pc 000280dd  /system/lib/libhwui.so (_ZN7android6Bitmap18allocateHeapBitmapEP8SkBitmapP12SkColorTable+45)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #06 pc 000fdb9d  /system/lib/libandroid_runtime.so (_ZL14Bitmap_creatorP7_JNIEnvP8_jobjectP10_jintArrayiiiiihP12_jfloatArrayS2_+365)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #07 pc 00aacd46  /system/framework/x86/boot-framework.oat (offset 0x5e6000) (android.graphics.Bitmap.nativeCreate+294)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #08 pc 00638ea2  /system/lib/libart.so (art_quick_invoke_static_stub+418)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #09 pc 00112b92  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+306)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #10 pc 003231ff  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+367)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #11 pc 0031cec3  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+803)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #12 pc 006217fd  /system/lib/libart.so (MterpInvokeStaticRange+397)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #13 pc 00629d21  /system/lib/libart.so (artMterpAsmInstructionStart+15265)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #14 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #15 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #16 pc 0031ce97  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+759)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #17 pc 006217fd  /system/lib/libart.so (MterpInvokeStaticRange+397)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #18 pc 00629d21  /system/lib/libart.so (artMterpAsmInstructionStart+15265)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #19 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #20 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #21 pc 0031bdb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+773)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #22 pc 0061fac4  /system/lib/libart.so (MterpInvokeStatic+484)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #23 pc 00629a21  /system/lib/libart.so (artMterpAsmInstructionStart+14497)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #24 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #25 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #26 pc 0031bdb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+773)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #27 pc 0061fac4  /system/lib/libart.so (MterpInvokeStatic+484)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #28 pc 00629a21  /system/lib/libart.so (artMterpAsmInstructionStart+14497)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #29 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #30 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #31 pc 0031bdb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+773)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #32 pc 0061fac4  /system/lib/libart.so (MterpInvokeStatic+484)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #33 pc 00629a21  /system/lib/libart.so (artMterpAsmInstructionStart+14497)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #34 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #35 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #36 pc 0031bdb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+773)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #37 pc 0061f3a3  /system/lib/libart.so (MterpInvokeInterface+1635)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #38 pc 00629aa1  /system/lib/libart.so (artMterpAsmInstructionStart+14625)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #39 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #40 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #41 pc 0031bdb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+773)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #42 pc 0061fac4  /system/lib/libart.so (MterpInvokeStatic+484)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #43 pc 00629a21  /system/lib/libart.so (artMterpAsmInstructionStart+14497)
11-01 13:56:52.802 16202-16202/? A/DEBUG:     #44 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #45 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #46 pc 0031ce97  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+759)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #47 pc 0062154e  /system/lib/libart.so (MterpInvokeDirectRange+462)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #48 pc 00629ca1  /system/lib/libart.so (artMterpAsmInstructionStart+15137)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #49 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #50 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #51 pc 0031ce97  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+759)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #52 pc 0061feb6  /system/lib/libart.so (MterpInvokeVirtualRange+838)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #53 pc 00629ba1  /system/lib/libart.so (artMterpAsmInstructionStart+14881)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #54 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #55 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #56 pc 0031bdb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+773)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #57 pc 0061e141  /system/lib/libart.so (MterpInvokeVirtual+881)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #58 pc 006298a1  /system/lib/libart.so (artMterpAsmInstructionStart+14113)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #59 pc 002f5f59  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+537)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #60 pc 002fdeda  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+234)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #61 pc 0031bdb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+773)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #62 pc 0061e141  /system/lib/libart.so (MterpInvokeVirtual+881)
11-01 13:56:52.803 16202-16202/? A/DEBUG:     #63 pc 006298a1  /system/lib/libart.so (artMterpAsmInstructionStart+14113)
11-01 13:56:53.663 1399-1399/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_05
```

**Comment by TWiStErRob** [comment]
Do you have GlideModule? Can you please include a Glide load line you're using? (If you can narrow down which one is crashing)

**Comment by TWiStErRob** [comment]
In the future please be careful when you're posting logs or stacks on GitHub, you just mentioned 60 issues which are not related to this one. See for example #10. Always wrap logs in triple backticks (code bloxk)

**Comment by MKevin3** [comment]
```
                val requestOptions = RequestOptions().override(image.maxWidth, image.maxHeight).placeholder(R.drawable.dress_inventory)

                Glide.with(context)
                        .load(detail.Images[0].ThumbUrl)
                        .apply(requestOptions)
                        .into(object : ViewTarget<View, Drawable>(image) {
                            override fun onResourceReady(resource: Drawable, glideAnimation: Transition<in Drawable>?) =
                                    image.setImageDrawable(resource.current)

                            override fun onLoadFailed(errorDrawable: Drawable?) = Unit
                        })

```

Not using a GlideModule

**Comment by sjudd** [comment]
Why are you using a custom ViewTarget? It looks like you're not implementing ``onLoadCleared``, which could cause you to try to draw recycled or invalid Bitmaps. 

I haven't specifically seen ``OpenGLRenderer: unknown bitmap configuration`` before. I'd sort of expect that to be related to Bitmap re-use or recycling, but it's odd. 

It's also possible something changed with how we handle Bitmap re-use that broke something in 4.3 I can't think of anything off the top of my head. If you do have a sample app you can reproduce this in that would definitely help.

**Comment by sjudd** [comment]
I found a bug I caused in 4.3.0, but it will only affect loads with transformations. Can you confirm that you're not using transformations at all?

**Comment by sjudd** [comment]
The bug I mentioned above should be fixed in 2371aa66594b160a74e1ddfbffc3e335152e3c55. 

If you're up for testing it, you can do so by [adding a SNAPSHOT dependency][1] on 4.4.0-20171102.052437-3 or higher. 

[1]: http://bumptech.github.io/glide/dev/snapshots.html#fixing-your-snapshot-dependency

**Comment by sjudd** [comment]
I'm going to assume this is fixed by 2371aa6, if you get the chance to test this, let me know.

**Comment by MKevin3** [comment]
I tried `implementation 'com.github.bumptech.glide:glide:4.4.0-20171102.183621-4'`
Still crashes


    On Thursday, November 2, 2017, 7:25:28 PM CDT, Sam <notifications@github.com> wrote:  
 
 
I'm going to assume this is fixed by 2371aa6, if you get the chance to test this, let me know.

**Comment by sjudd** [comment]
Are you able to answer any of the questions above?

Can you reproduce this in a sample app and attach it here?

**Comment by sjudd** [comment]
It would also help if you're able to attach one of the images that triggers the crash.

**Comment by sjudd** [comment]
Actually it looks like you might have manually enabled the open gl rendered in developer settings? If so that's an experimental setting, try disabling it.

**Comment by MKevin3** [comment]
![dress_inventory](https://user-images.githubusercontent.com/2380650/32465874-a5f26000-c30a-11e7-9284-59808200e9c4.png)

This is the placeholder image I am using. I will have track down the Amazon image if that will not trigger it for you. All code is Kotlin, doubt that makes any difference. App has full sign in for images it uses so making a sample app is a bit more difficult.

I don't have anything enabled in Developer Options under the Drawing area so I don't think Open GL is part of it.

**Comment by sjudd** [comment]
Thanks for the placeholder. I'm not able to reproduce when using it as a placeholder or as the model on an x86 API 26 emulator on osx.
