### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by cabelloruizcarlos** [bumptech/glide#3099]
**Glide Version**: implementation 'com.github.bumptech.glide:glide:4.3.1'
**I'm using Contentful**
    implementation 'com.contentful.java:java-sdk:7.6.2'
    implementation 'com.squareup.okhttp3:okhttp:3.8.1'
**Another libraries that I'm using, but not for loading images**: 
implementation 'com.squareup.retrofit2:retrofit:1.9.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.8.1

**Device/Android Version**: I'm using Firebase Crashlytics. The count of crashes from Monday 14th to today(18th at 12PM(London time)) is 11, these are the devices:
- Galaxy S7 (Not Rooted) Running 7.0(Nougat) 3 ocurrences
- Galaxy S7 Edge (Not Rooted) Running 7.0(Nougat) 1 occurrence
- Galaxy S8 (Not Rooted) Running 7.0(Nougat) 1 occurrence
- Huawei P8 (Not Rooted) Running 6.0(Marshmallow) 2 occurrences
- HTC OnePlus-A3003 (Not Rooted) Running 8.0(Oreo) 1 occurrence

**Issue details / Repro steps / Use case background**:  I uploaded an screenshot of the crash report
![screen shot 2018-05-18 at 11 25 34](https://user-images.githubusercontent.com/7534807/40230898-265a3204-5a91-11e8-86a8-f22928a2a8cd.png)

I never reproduce with the testing devices at my office. Looks like Glide is using the dynamic resource ID and its crashing when it is auto-generated again, but I'm not sure about it. I added the error method trying to avoid the crash but its still happening.
I'm using the same code to load all the images of the app(even animated Gifs) and Its working like a charm

This is the method I'm using to load the url into the ImageView:
```java
       private static void setImage(ImageView iv, String imageUrl, int localImageResource, ImageView.ScaleType scaleType) {

        if (!Util.isOnline())
            return;

        if (Util.isImageNameValid(imageUrl))
            return;

        if (scaleType != null) 
            iv.setScaleType(scaleType);
        
        RequestManager requestManager = Glide.with(iv.getContext());
        RequestOptions options = new RequestOptions();
        RequestBuilder<Drawable> builder = null;
        // Carlos: Firebase BugFixing: Resources$NotFoundException - ResourcesImpl.getValue(android.content.res.Resources$NotFoundException: Resource ID #0x57)
        // Carlos: I added the error method along with the blank drawable
        requestManager.clear(iv);
        if (!NullSafe.isEmpty(imageUrl)) {
            if (localImageResource != 0)
                options.placeholder(localImageResource);
            builder = requestManager.load(imageUrl).apply(options.diskCacheStrategy(DiskCacheStrategy.RESOURCE).error(R.drawable.blank));
        } else if (localImageResource > 0) {
            builder = requestManager.load(localImageResource);
        } else {
            return;
        }
        builder.into(iv);
    }
```
This is the sample of a Contentful url: https://images.ctfassets.net/[contentful object id]/New_Cocktail.jpg?fit=fill&w=1080&h=1050

**Layout XML**: The ImageView is a custom view extending from android.support.v7.widget.AppCompatImageView 

**Stack trace / LogCat**: I couldn't reproduce it so far so I only have the Firebase report. I think thats one of the reasons why I couldn't solve it yet

Any help of any kind could be amazing!!! I don't know what should I change or what I'm doing wrong. It happens sometimes and I only have the report from Firebase Crashlytics

**Comment by sjudd** [comment]
Fixed in 963191a6554449531fd96feba6f85902b53af20a probably, please re-open if you can reproduce on 4.7.1 or higher.

**Comment by cabelloruizcarlos** [comment]
Hi again!! I updated the Glide version but it looks like the issue is not fixed because in 4 days I received 8 crashes.

**Glide Version**: implementation 'com.github.bumptech.glide:glide:4.7.1'

**Device/Android Version**: 
Galaxy S7 (Not Rooted) Running 7.0(Nougat) 3 occurrences
Galaxy S6 (Not Rooted) Running 7.0(Nougat) 1 occurrence
BlackBerry BBB100-2(Not Rooted) 7.1.1(Nougat) 1 occurrence
Xperia X(Not Rooted) Running 8.0.0(Oreo) 1 occurrence     
Galaxy S8 (Not Rooted) Running 8.0.0(Oreo) 2 occurrences

**This is the crash**
![screen shot 2018-06-08 at 11 09 08](https://user-images.githubusercontent.com/7534807/41152776-955cf250-6b0c-11e8-8591-ffa38a3f201c.png)
