### ISSUE TITLE
GIFs drop frames when many of them are displayed

### ISSUE THREAD

**Issue by shewenbiao** [bumptech/glide#637]
Hi,
   
   * I use glide to load gif, it can be loaded and displayed in ImageView, but the display is not normal.

   * I use another open source project([GifDrawable](https://github.com/koral--/android-gif-drawable)) that also support gif, the gif can be loaded and displayed normally in ImageView.

   * Use glide and gifdrawable to load gif effect is as follows.

     Use glide | Use gifdrawable
     ------------- | ---------------------
     https://www.dropbox.com/s/doe062ghzpp5ryg/device-2015-09-18-113927.mp4?dl=0 | https://www.dropbox.com/s/whuooxsn8wdd2kr/device-2015-09-18-114503.mp4?dl=0

   * I suspect this is a bug of glide.

**Comment by TWiStErRob** [comment]
Can you please point out the problem, I can't see it?

**Comment by shewenbiao** [comment]
Can you access to  above two links? If you can, you will see a short video and find the difference if you compare two videos carefully.The problem is the gif doesn't play smoothly, it lose frames.In gridview, the first gif seems most obvious, you can observe the changes of it's hand.

My English is poor, I hope you can understand.Thanks for your help.

**Comment by shewenbiao** [comment]
Hi, @TWiStErRob 
Can you see the problem? I've been waiting for your reply, but you've never given me back. I want to know whether it is a bug of Glide.There also may be my usage isn't right. My code is as follows:
```javascript
public class StickerDataFetcher implements DataFetcher<InputStream>{
    private Context context;
    private String packageName;
    private String filePath;
    private String fileName;
    private InputStream mInputStream;
    public StickerDataFetcher(Context context, StickerModel stickerModel) {
        this(context, stickerModel.packageName, stickerModel.filePath, stickerModel.fileName);
    }

    public StickerDataFetcher(Context context, String packageName, String filePath, String fileName) {
        this.context = context;
        this.packageName = packageName;
        this.filePath = filePath;
        this.fileName = fileName;
    }
    @Override
    public InputStream loadData(Priority priority) throws Exception {
        mInputStream = fetchStream(context, packageName, filePath, fileName);
        return mInputStream;
    }

    @Override
    public void cleanup() {
        if (mInputStream != null) {
            try {
                mInputStream.close();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                mInputStream = null;
            }
        }
    }

    @Override
    public String getId() {
        return packageName + fileName;
    }

    @Override
    public void cancel() {

    }

    private InputStream fetchStream(Context context, String packageName, String filePath, String fileName) {
        Context desContext;
        InputStream inputStream = null;
        try {
            desContext = context.createPackageContext(packageName, Context.CONTEXT_IGNORE_SECURITY);
            if (desContext != null) {
                AssetManager assetManager = desContext.getAssets();
                inputStream = assetManager.open(filePath + File.separator + fileName);
            }
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
            inputStream = null;
        }
        return inputStream;
    }
}

class StickerStreamLoader implements StreamModelLoader<StickerModel> {
    private Context context;
    public StickerStreamLoader(Context context) {
        this.context = context.getApplicationContext();
    }

    @Override
    public DataFetcher<InputStream> getResourceFetcher(StickerModel model, int width, int height) {
        return new StickerDataFetcher(context, model);
    }

    public static class Factory implements ModelLoaderFactory<StickerModel, InputStream> {
        @Override public ModelLoader<StickerModel, InputStream> build(Context context, GenericLoaderFactory factories) {
            return new StickerStreamLoader(context);
        }
        @Override public void teardown() {
            // nothing to do
        }
    }
}

public class StickerStreamModule implements GlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {

    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        glide.register(StickerModel.class, InputStream.class, new StickerStreamLoader.Factory());
    }
}

public class StickerModel {
    public String packageName;
    public String filePath;
    public String fileName;

    public StickerModel(String packageName, String filePath, String fileName) {
        this.packageName = packageName;
        this.filePath = filePath;
        this.fileName = fileName;
    }
}

Glide.with(getContext()).load(new StickerModel(pkg, filePath, name)).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(holder.stickerImg);
```
Can you give me a answer? Thanks.

**Comment by TWiStErRob** [comment]
Sorry, I didn't have place where I can watch the videos side-by-side until now. I couldn't see the diff on my phone when watching them one after the other. I can see now that Glide is indeed skipping frames. Because you ran the same app without framedropping on the same phone, we can assume that Glide should be able to have to CPU power to load them too.

Your usage looks good apart from a few minor things that don't affect this issue. There's one thing worth trying: change `DiskCacheStrategy.SOURCE` to `DiskCacheStrategy.ALL` or just simply remove it. It'll delay displaying the image at first, but then it'll possibly stop skipping frames because the resizing step is not happening. Another alternative to the above is: use SOURCE and `.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` or `.dontTransform()`. So here are the options you should try:
```java
// original
....load(...).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(...
// do the resizing beforehand and also save it to disk cache
....load(...).diskCacheStrategy(DiskCacheStrategy.ALL).into(...
// try to prevent resampling of each frame
....load(...).diskCacheStrategy(DiskCacheStrategy.SOURCE).override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).into(...
// try to prevent resizing and load the original sized GIF frames
....load(...).diskCacheStrategy(DiskCacheStrategy.SOURCE).dontTransform().into(...
```
These are wild guesses only, I'm not sure if they'll have a good effect, but it's worth trying to get you closer to what GifDrawable offers (they probably don't resize the frames just load them).
@sjudd Do you have any other ideas to try?

Here are the minor issues issues, telling you to prevent possible future bugs:
 * `e.printStackTrace()` is evil, never use it, check out [`Log`](http://developer.android.com/reference/android/util/Log.html) instead.
 * `getId()` is missing `filePath`  
currently `/folder1/image1` will have a cache collision with `/folder2/image1`
 * `getId()` is missing a separator  
currently `image` in `package` will collide with `geimage` in `packa` because of the simple concatenation

To alleviate these last two I suggest this: get rid of `filePath` and initialize `this.fileName = filePath + File.separator + fileName` and change `packageName + fileName` in `getId()` to `packageName + ":" + fileName`.

**Comment by shewenbiao** [comment]
Anyway, I am very grateful for your reply and suggestions. I will try
it and let you know the results


2015-10-02 21:37 GMT+08:00 Róbert Papp <notifications@github.com>:

**Comment by shewenbiao** [comment]
@TWiStErRob I had try your suggestions, but they didn't have a good effect. Do you have any other ideas to try?

**Comment by TWiStErRob** [comment]
Not really, sorry. @sjudd?

**Comment by sjudd** [comment]
No ideas yet, I think there is some case where GIF playing gets slower than normal, though I haven't tracked down what it might be. It's possible our threading model is too limited for many GIFs and that we'd be better off having a thread per gif rather than a shared thread pool.

**Comment by shewenbiao** [comment]
@sjudd @TWiStErRob 
> It's possible our threading model is too limited for many GIFs and that we'd be better off having a thread per gif rather than a shared thread pool.

Can I verify this issue? if I can , is there a good way for me to quickly verify this issue? My project is developing on AndroidStudio, I use Gradle:
```javascript
repositories {
    mavenCentral()
}

dependencies {
    compile 'com.github.bumptech.glide:glide:3.6.1'
    compile 'com.android.support:support-v4:19.1.0'
}
```
in build.gradle file of app.However, using this method, I have no way to verify this issue.In addition, using jar or Maven also can't do it. I think I have to modify the code if I want to verify this issue. Do you have a good idea for me?

**Comment by TWiStErRob** [comment]
Sam's talking about this I think: the GIF frame scheduling is done on the main UI thread: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/resource/gif/GifFrameLoader.java#L50

@sjudd But this doesn't mean that's the problem. I'd say there are too many frames being decoded in the background and some of them can't deliver in time because of Glide internal scheduling.

@shewenbiao try to increase the number of threads in Glide's internal pool in a `GlideModule` (Defaults are [here](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L168)):
```java
builder.setDiskCacheService(new FifoPriorityThreadPoolExecutor(4));
// or
builder.setResizeService(new FifoPriorityThreadPoolExecutor(4));
```
Let us know if one or both of them make the situation better.

**Comment by shewenbiao** [comment]
@TWiStErRob I will try it and let you know the results as soon as possible

**Comment by shewenbiao** [comment]
@TWiStErRob 
>builder.setDiskCacheService(new FifoPriorityThreadPoolExecutor(4));
// or
builder.setResizeService(new FifoPriorityThreadPoolExecutor(4));

Both of them don't make the situation better.

I changed the way to display gif images in my project.My ideas is this:
   * First, I used glide to load gif images from asset's folder but not let it display in ImageView.
   * Then, I used [Fresco](http://frescolib.org/docs/index.html#_) to get gif images from Glide's cache and I found the gif display normally.


The code as following:
```javascript
  class GetCacheTask extends AsyncTask<StickerModel, Void, File>{
        private final Context context;
        private final SimpleDraweeView simpleDraweeView;
        public GetCacheTask(Context context, SimpleDraweeView simpleDraweeView) {
            this.context = context;
            this.simpleDraweeView = simpleDraweeView;
        }

        @Override
        protected File doInBackground(StickerModel... params) {
            FutureTarget<File> targetFuture = Glide.with(context)
                    .load(params[0])
                    .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
            File file;
            try {
                file = targetFuture.get();
            } catch (Exception e) {
                file = null;
            }
            return file;
        }

        @Override
        protected void onPostExecute(File file) {
            super.onPostExecute(file);
            if (file == null) {
                return;
            }
            Uri uri = Uri.fromFile(file);
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setUri(uri)
                    .setAutoPlayAnimations(true)
                    .build();
            simpleDraweeView.setController(controller);
        }
    }

 new GetCacheTask(getContext(), holder.stickerImg).executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, new StickerModel(pkg, filePath, fileName));
```
So, I suspect the problem is likely to arise in `.into(holder.stickerImg)`.
```javascript
Glide.with(getContext()).load(new StickerModel(pkg, filePath, name)).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(holder.stickerImg);
```
What do you think?

**Comment by TWiStErRob** [comment]
If it works, use it :) The problem that may come up is cancelling loads when a list view is scrolled.

You could also use Glide to end up with a GifDrawable you mentioned above. That way you'll end up with a `GenericRequestBuilder<StickerModel, InputStream, byte[], GifDrawable>` for example.

Ask yourself these:
 * Do I need to copy the files over to Glide cache? (same device, same storage/sdcard)
 * Do I need Glide's model loader mechanis if I'm using an async task (background thread) anyway and end up with a File?

Also note that GifDrawable has an assets constructor:
```java
holder.stickerImg.setImageDrawable(new GifDrawable(context.createPackageContext(packageName, Context.CONTEXT_IGNORE_SECURITY).getAssets(), filePath + File.separator + fileName)));
```

**Comment by shewenbiao** [comment]
@TWiStErRob

 Glide is powerful than other image loading frameworks. It is simple to use and very powerful. I really like the Glide. GifDrawable that I mentioned above only can support animated GIFs. In my project, some stickers are animated GIFs, some stickers are static images. Therefore GifDrawable does not meet the needs of the project. Using Fresco, a new problem that will come up is cancelling loads when a list view is scrolled.

Compared to other frameworks, glide is better suited the project needs. I'm looking forward to glide to improve GIF dropped frames issue.

Thank you for always helping me solve the problem.

**Comment by TWiStErRob** [comment]
Do you know which file is GIF and which isn't? Like a simple `fileName.endsWith(".gif")` because then you could apply different strategies:
* normal load with nice model loader for non-gif
* manually set GifDrawable for GIFs (or force it through Glide, but the other oneliner seems easier)

> I'm looking forward to glide to improve GIF dropped frames issue.

Would it be possible for you to create a sample project for us, including GIF resources, so it's possible to simply reproduce and see the issue and the effects of any fixes made?

**Comment by shewenbiao** [comment]
Thank you for reminding and recommendations, I will try it.

>Would it be possible for you to create a sample project for us, including GIF resources

Of course, I will create it as soon as possible and reply you here.

**Comment by shewenbiao** [comment]
@TWiStErRob 
>Do you know which file is GIF and which isn't? Like a simple fileName.endsWith(".gif") because then you could apply different strategies:
* normal load with nice model loader for non-gif
* manually set GifDrawable for GIFs (or force it through Glide, but the other oneliner seems easier)

Thank you for your suggestion. Now the situation is much better than before.
I have created a simple project(https://github.com/shewenbiao/StickerDemo), including GIF resources.

**Comment by TWiStErRob** [comment]
@sjudd according to @shewenbiao allowing more threads for `FifoPriorityThreadPoolExecutor` didn't make any difference I started to think about another possibility:
```java
// The minimum frame delay in hundredths of a second.
static final int MIN_FRAME_DELAY = 3;
// The default frame delay in hundredths of a second for GIFs with frame delays less than the minimum.
static final int DEFAULT_FRAME_DELAY = 10;
if (delayInHundredthsOfASecond < MIN_FRAME_DELAY) {
    delayInHundredthsOfASecond = DEFAULT_FRAME_DELAY;
}
```
To check this I put a non-suspending logging breakpoint which outputs values for `delayInHundredthsOfASecond`, and indeed there are some 10ms frames in his sample project: I also noticed that the last frame is not held long enough (or at all for example in case of 1st image); this is the most visible thing, because the gif jumps.

| Frame Delay (1/100th sec) | Count |
---|---
|1|12|
|3|32|
|4|30|
|5|68|
|6|4|
|7|2|
|8|8|
|9|2|
|10|62|
|15|10|
|20|42|
|50|22|
|50|22|
|80|6|
|100|4|
|150|4|
|200|4|
|250|2|

I tried to remove the above condition locally, but it actually made the situation worse. What I don't understand is why set an originally short frame time to an extremely (relative) long one?
Browsers do this too: http://humpy77.deviantart.com/journal/Frame-Delay-Times-for-Animated-GIFs-214150546, if a frame is designed to be 10ms long, by display it was 100ms, however 30ms is displayed as 30ms... that just doesn't make sense to me.

**Comment by sjudd** [comment]
There's an issue somewhere buried in here that talks about this. The reasoning seems to be that IE used to have this behavior a long time ago, so there's a set of GIFs out there that either didn't set a real frame delay or set it to something tiny because either way the GIF looked fine in IE.

Since the GIFs work in IE, it looks like a bug when they don't work elsewhere, and so everyone started using this behavior. 

I'm not opposed to decreasing it, I believe Chrome and other browsers have been lowering the limits.

**Comment by TWiStErRob** [comment]
Hmm, ok, what sounds reasonlable, however just for fun: imagine CSS3 was based on IE6's CSS behavior.
The bigger problem I think is the last frame being displayed too short.

**Comment by esevece** [comment]
@TWiStErRob I have the problem you mention that the last frame is being displayed too short. My GIF file is composed of 3 frames. I noticed that the GIF gets stuck on the second frame which makes the third (and last) frame shorter. The problem is not reproducible on any browser or GIF viewer.

**Comment by TWiStErRob** [comment]
@esevece what you mention may have been fixed in #1091, should available as [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots). Please give it a spin.

**Comment by esevece** [comment]
Thank you @TWiStErRob! Works perfect now!

**Comment by shewenbiao** [comment]
@TWiStErRob 
This problem has been solved  in glide version 3.7.0 yet? I have tried with [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots), it works perfect now!

**Comment by TWiStErRob** [comment]
I didn't fix this explicitly. If you confirm that just upgrading from 3.7.0 to 3.8.0 solves the issue, then I think this bug is a duplicate of #1060: probably the jumpiness/skipping was caused by showing the last 2 frames (last one is usually held longer) for the wrong amount of time, giving the illusion of skip frame.

Just to be sure: you didn't change yourtest device to a new powerhouse, right?

**Comment by shewenbiao** [comment]
@TWiStErRob 
Yes, I'm sure I didn't change my test device and the GIFs drop frames issue has been fixed in [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots), but there have an another problem. The  problem is it will be delayed for some time before playing if load many GIFs.

**Comment by TWiStErRob** [comment]
I think we should start a new issue for that. I'll close this, as it's fixed.
Please open a new one with full description as if we had never talked before.

**Comment by shewenbiao** [comment]
OK, I will do it.
