### ISSUE TITLE
Some GIFs overdraw on previous frames

### ISSUE THREAD

**Issue by Alluretears** [bumptech/glide#836]
**Glide Version**: 3.6.1
**Device**: Nexus 5/6.0(API 23)
When loading the transparent background gif images, there will be remnant, as shown below.
![device-2015-12-23-130049](https://cloud.githubusercontent.com/assets/7030019/11971353/21872386-a977-11e5-92ff-aa0251fa9061.gif)

**Glide load line**:
```java
Glide.with(this).load("http://7rf2lu.com2.z0.glb.qiniucdn.com/1450421326882.gif").into(imageView);
```

**Layout XML**:
```xml
<ImageView
    android:id="@+id/img_gif_Glide"
    android:layout_width="160dp"
    android:layout_height="160dp"/>
```

**Comment by TWiStErRob** [comment]
I think this is already fixed by #620, but it's not released yet, only available in [`4.0.0-SNAPSHOT`](https://github.com/bumptech/glide/wiki/Snapshots). Can you please try that?

**Comment by Alluretears** [comment]
@TWiStErRob Thank you very much for your help. I tried 4.0.0-SNAPSHOT(glide-4.0.0-20151212.212519-126.jar)but it did not fix，the same  effect as above:(

**Comment by TWiStErRob** [comment]
@kojilin can you please help here?

**Comment by kojilin** [comment]
@TWiStErRob @Alluretears I have tested and found the original gif's second frame's disposal is 1(DISPOSAL_NONE). So basically, I think the behavior is correct, but I see browsers(chrome, firefox, safari) are all clear last frame before playing first frame(Does it means first frame should not care last frame's disposal value?I'm not sure yet;;).

**Comment by Alluretears** [comment]
@TWiStErRob @kojilin Thanks,How can I clear the last frame?

**Comment by kojilin** [comment]
@Alluretears if u don't want to change the code of glide, u need to confirm ur gif has disposal flag at last frame. I'm not very familiar with image editing tool, but gimp gif export can select apply replace option to every frame.

But I think follow browsers behavior is needed. maybe revert #620 and check if previous frame is null, then fill the default color?

**Comment by TWiStErRob** [comment]
@kojilin thank you very much for looking. @sjudd what do you think about his idea?

**Comment by sjudd** [comment]
+1, let's follow the browser behavior.

**Comment by TWiStErRob** [comment]
This is fixed for v4.
